// S3 Image utilities for Lithuanian recipe website
// Optimized for SEO and fast loading with blur placeholders

export interface RecipeImage {
  src: string;
  alt: string;
  width: number;
  height: number;
  blurHash?: string; // Generated by Next.js, optional for backward compatibility
}

// S3 Configuration
const S3_CONFIG = {
  bucketName: 'receptu-images',
  region: 'eu-north-1',
  baseUrl: 'https://receptu-images.s3.eu-north-1.amazonaws.com',
};

/**
 * Generate S3 URL for recipe image
 */
export function generateS3ImageUrl(filename: string, folder?: string): string {
  const path = folder ? `${folder}/${filename}` : filename;
  return `${S3_CONFIG.baseUrl}/${path}`;
}

/**
 * Create optimized image object for recipes
 */
export function createRecipeImage(
  filename: string,
  alt: string,
  width: number = 1200,
  height: number = 800,
  folder?: string
): RecipeImage {
  const src = generateS3ImageUrl(filename, folder);

  return {
    src,
    alt,
    width,
    height,
    // Future: Add blurHash generation
    // blurHash: generateBlurHash(src),
  };
}

/**
 * Generate blur placeholder for better loading experience
 * Creates a simple base64 data URL that Next.js can use as blurDataURL
 */
export function generateBlurPlaceholder(width: number = 1200, height: number = 800): string {
  // Create a simple 1x1 pixel blur placeholder
  // This is what Next.js typically generates automatically
  const canvas = `
    <svg width="${width}" height="${height}" xmlns="http://www.w3.org/2000/svg">
      <defs>
        <linearGradient id="grad" x1="0%" y1="0%" x2="100%" y2="100%">
          <stop offset="0%" style="stop-color:#f3f4f6;stop-opacity:1" />
          <stop offset="100%" style="stop-color:#e5e7eb;stop-opacity:1" />
        </linearGradient>
      </defs>
      <rect width="100%" height="100%" fill="url(#grad)" />
      <circle cx="50%" cy="40%" r="20" fill="#d1d5db" opacity="0.5"/>
      <rect x="30%" y="60%" width="40%" height="8" fill="#d1d5db" opacity="0.3" rx="4"/>
      <rect x="35%" y="72%" width="30%" height="6" fill="#d1d5db" opacity="0.2" rx="3"/>
    </svg>
  `;

  return `data:image/svg+xml;base64,${Buffer.from(canvas).toString('base64')}`;
}

/**
 * Generate a simple blur data URL for Next.js Image component
 * This mimics what Next.js would generate automatically
 */
export function generateNextJSBlurPlaceholder(): string {
  // Simple 8x8 pixel blur placeholder (similar to Next.js default)
  const blurSvg = `
    <svg width="8" height="8" xmlns="http://www.w3.org/2000/svg">
      <filter id="blur">
        <feGaussianBlur stdDeviation="2"/>
      </filter>
      <rect width="100%" height="100%" fill="#f3f4f6" filter="url(#blur)"/>
    </svg>
  `;

  return `data:image/svg+xml;base64,${Buffer.from(blurSvg).toString('base64')}`;
}

/**
 * Validate S3 image URL
 */
export function isValidS3ImageUrl(url: string): boolean {
  try {
    const urlObj = new URL(url);
    return urlObj.hostname.includes('receptu-images.s3') ||
           urlObj.hostname.includes('amazonaws.com');
  } catch {
    return false;
  }
}

/**
 * Get optimized image props for Next.js Image component
 * Next.js will automatically generate WebP/AVIF formats and blur placeholder
 */
export function getOptimizedImageProps(image: RecipeImage, priority: boolean = false) {
  return {
    src: image.src,
    alt: image.alt,
    width: image.width,
    height: image.height,
    priority,
    placeholder: 'blur' as const,
    blurDataURL: image.blurHash || generateBlurPlaceholder(image.width, image.height),
    sizes: "(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw",
    quality: 85,
  };
}

/**
 * Convert any image format to standardized S3 RecipeImage format
 * Handles: string URLs, legacy objects, and new S3 objects
 */
export function convertToRecipeImage(imageInput: any): RecipeImage {
  // Handle string URLs (legacy)
  if (typeof imageInput === 'string') {
    return createRecipeImage(
      imageInput.split('/').pop() || 'placeholder.jpg',
      'Recipe image',
      1200,
      800
    );
  }

  // Handle new S3 format (current schema)
  if (imageInput?.src) {
    return {
      src: imageInput.src,
      alt: imageInput.alt || 'Recipe image',
      width: imageInput.width || 1200,
      height: imageInput.height || 800,
      blurHash: imageInput.blurHash, // Optional, Next.js will generate if missing
    };
  }

  // Handle legacy format with 'url' property
  if (imageInput?.url) {
    return {
      src: isValidS3ImageUrl(imageInput.url)
        ? imageInput.url
        : generateS3ImageUrl('placeholder.jpg'),
      alt: imageInput.alt || 'Recipe image',
      width: imageInput.width || 1200,
      height: imageInput.height || 800,
    };
  }

  // Fallback
  return createRecipeImage('placeholder.jpg', 'Recipe image');
}

/**
 * Generate responsive image sizes for different use cases
 */
export const IMAGE_SIZES = {
  // Recipe card thumbnails
  thumbnail: {
    width: 400,
    height: 300,
    sizes: "(max-width: 768px) 50vw, (max-width: 1200px) 33vw, 25vw"
  },
  // Recipe detail page hero
  hero: {
    width: 1200,
    height: 800,
    sizes: "(max-width: 768px) 100vw, (max-width: 1200px) 80vw, 60vw"
  },
  // Category page banners
  banner: {
    width: 1200,
    height: 400,
    sizes: "100vw"
  }
};

/**
 * Helper to create image object for different contexts
 */
export function createContextualImage(
  filename: string,
  alt: string,
  context: keyof typeof IMAGE_SIZES = 'hero',
  folder?: string
): RecipeImage {
  const size = IMAGE_SIZES[context];
  return createRecipeImage(filename, alt, size.width, size.height, folder);
}